<?php

defined('HOSTCMS') || exit('HostCMS: access denied.');

/**
 * Counter_Bot
 *
 * @package HostCMS
 * @subpackage Counter
 * @version 7.x
 * @author Hostmake LLC
 * @copyright © 2005-2024 ООО "Хостмэйк"(Hostmake LLC), http://www.hostcms.ru
 */
class Counter_Bot
{
	static protected $_aBots = array(
		'360Spider',
		'404checker',
		'404enemy',
		'Abonti',
		'Aboundex',
		'acebookexternalhit',
		'Acunetix',
		'AdlesseBot',
		'ADmantX',
		'admantx-adform',
		'Adsbot',
		'adscanner',
		'AfD-Verbotsverfahren',
		'AHC/2.1',
		'AhrefsBot',
		'AIBOT',
		'AiHitBot',
		'aiohttp',
		'Aipbot',
		'Alexibot',
		'ALittle Client',
		'Alligator',
		'AllSubmitter',
		'AlphaBot',
		'Amazonbot',
		'Anarchie',
		'Anarchy',
		'Anarchy99',
		'Ankit',
		'Anthill',
		'Apache-HttpClient/5',
		'Apexoo',
		'app.hypefactors.com',
		'AppEngine-Google',
		'Applebot',
		'archive.org_bot',
		'arquivo.pt',
		'arquivo-web-crawler',
		'Aspiegel',
		'ASPSeek',
		'Asterias',
		'Astute SRM',
		'Atomseobot',
		'Attach',
		'autoemailspider',
		'AwarioRssBot',
		'AwarioSmartBot',
		'axios',
		'BackDoorBot',
		'backlink-check',
		'BacklinkCrawler',
		'BackStreet',
		'BackWeb',
		'Badass',
		'Baidu',
		'Baiduspider',
		'Bandit',
		'Barkrowler',
		'BatchFTP',
		'Battleztar Bazinga',
		'BazQuxBot',
		'BBBike',
		'BDCbot',
		'BDFetch',
		'BehloolBot',
		'BetaBot',
		'Bigfoot',
		'Bingbot',
		'Bitacle',
		'bitlybot',
		'Black Hole',
		'Blackboard',
		'BlackWidow',
		'BLEXBot',
		'Blow',
		'BlowFish',
		'Boardreader',
		'Bolt',
		'BotALot',
		'Brandprotect',
		'Brandwatch',
		'BTWebClient',
		'Buck',
		'Buddy',
		'BuiltBotTough',
		'BuiltWith',
		'Bullseye',
		'BunnySlippers',
		'Butterfly',
		'BuzzSumo',
		'cah.io.community',
		'Calculon',
		'CATExplorador',
		'CazoodleBot',
		'CCBot',
		'Cegbfeieh',
		'CensysInspect',
		'CheeseBot',
		'CherryPicker',
		'CheTeam',
		'ChinaClaw',
		'Chlooe',
		'Citoid',
		'Claritybot',
		'clark-crawler',
		'Cliqzbot',
		'Cloud mapping',
		'Cloudflare SpeedTest',
		'Coccocbot',
		'Cocolyzebot',
		'CODE87',
		'Cogentbot',
		'cognitiveseo',
		'Collector',
		'com.plumanalytics',
		'CommonCrawler',
		'Copier',
		'CopyRightCheck',
		'Copyscape',
		'Cosmos',
		'Craftbot',
		'crawl.sogou.com',
		'crawler.feedback',
		'crawler4j',
		'Crawling at Home Project',
		'CrazyWebCrawler',
		'Crescent',
		'CriteoBot',
		'CrunchBot',
		'cs.daum.net',
		'CSHttp',
		'Curious',
		'curl/7',
		'Custo',
		'CyotekWebCopy',
		'DatabaseDriverMysqli',
		'DataCha0s',
		'dataforseo.com',
		'DataForSeoBot',
		'DBLBot',
		'Demon',
		'Deusu',
		'Devil',
		'Digincore',
		'DigitalPebble',
		'DIIbot',
		'Dirbuster',
		'Discobot',
		'Discoverybot',
		'Dispatch',
		'DittoSpyder',
		'dlvr.it',
		'DnBCrawler-Analytics',
		'DnyzBot',
		'DomainAppender',
		'DomainCrawler',
		'Domains Project',
		'DomainSigmaCrawler',
		'domainsproject.org',
		'DomainStatsBot',
		'DomCopBot',
		'Dotbot',
		'Down/5',
		'Download Wonder',
		'Dragonfly',
		'Drip',
		'DSearch',
		'DTS Agent',
		'DuckDuckBot',
		'DuckDuckGo' ,
		'EasyDL',
		'Ebingbong',
		'eCairn-Grabber',
		'eCatch',
		'Ecxi',
		'EirGrabber',
		'EMail Siphon',
		'EMail Wolf',
		'EroCrawler',
		'Evil',
		'Exabot',
		'Express WebPictures',
		'ExtLinksBot',
		'Extractor',
		'ExtractorPro',
		'Extreme Picture Finder',
		'EyeNetIE',
		'Ezooms',
		'facebookexternalhit',
		'facebookscraper',
		'FDM',
		'feedbot',
		'Feeder',
		'Feedfetcher-Google',
		'Feedly',
		'FemtosearchBot',
		'FHscan',
		'Fimap',
		'FlipboardProxy',
		'Flunky',
		'Foobot',
		'Freeuploader',
		'FrontPage',
		'Fuzz',
		'FyberSpider',
		'Fyrebot',
		'GalaxyBot',
		'GarlikCrawler',
		'Genieo',
		'GermCrawler',
		'Getintent',
		'GetRight',
		'getstream.io/winds',
		'GetWeb',
		'Gigabot',
		'G-i-g-a-b-o-t',
		'Go!Zilla',
		'Googlebot',
		'GoogleProducer',
		'GoogleOther',
		'gopher',
		'Gotit',
		'GoZilla',
		'Grabber',
		'GrabNet',
		'Grafula',
		'GrapeFX',
		'GrapeshotCrawler',
		'GridBot',
		'grokkit-crawler',
		'GroupHigh',
		'Haansoft',
		'HaosouSpider',
		'Harvest',
		'Havij',
		'HEADMasterSEO',
		'Heritrix',
		'Hloader',
		'HMView',
		'HonoluluBot',
		'HTMLparser',
		'HTTP::Lite',
		'HTTP_Request2',
		'HTTrack',
		'Humanlinks',
		'HybridBot',
		'ia_archiver',
		'Iblog',
		'ibwww-perl',
		'IDBot',
		'IDBTE4M',
		'Id-search',
		'IlseBot',
		'Image Fetch',
		'Image Sucker',
		'ImageFetcher' ,
		'InAGist',
		'IndeedBot',
		'InfoNaviRobot',
		'InfoTekies',
		'instabid',
		'Intelliseek',
		'InterGET',
		'Internet Ninja',
		'InternetSeer',
		'internetVista monitor',
		'ips-agent',
		'Iria',
		'IRLbot',
		'Iskanie',
		'IstellaBot',
		'Jbrofuzz',
		'JennyBot',
		'JetCar',
		'Jetslide',
		'Jetty',
		'JikeSpider',
		'JOC Web Spider',
		'Jyxobot',
		'KatBot',
		'Kenjin Spider',
		'Keybot Translation-Search-Machine',
		'Keyword Density',
		'Kinza',
		'Kozmosbot',
		'Kraken',
		'Lanshanbot',
		'Larbin',
		'Leap',
		'LeechFTP',
		'LeechGet',
		'LexiBot',
		'Lftp',
		'LibWeb',
		'Libwhisker',
		'LieBaoFast',
		'Lightspeedsystems',
		'Likse',
		'Linguee Bot',
		'Linkbot',
		'linkdex',
		'linkdexbot',
		'LinkextractorPro',
		'linkfluence.com',
		'LinkpadBot',
		'LinkScan',
		'LinksManager',
		'LinkWalker',
		'Lipperhey',
		'Litemage_walker',
		'LivelapBot',
		'Lmspider',
		'LNSpiderguy',
		'Ltx71',
		'Magnet',
		'magpie-crawler',
		'Mail.RU',
		'Majestic SEO',
		'Majestic-SEO',
		'Majestic12',
		'MarkMonitor',
		'MarkWatch',
		'Mass Downloader',
		'Masscan',
		'Mata Hari',
		'MauiBot',
		'MaxPointCrawler',
		'Meanpath',
		'Mediapartners-Google',
		'Mediatoolkitbot',
		'Mediawords',
		'MegaIndex',
		'merlinkbot',
		'metadataparser',
		'MetadataScraper',
		'MetaInspector',
		'MetaJobBot',
		'MetaURI',
		'MIIxpc',
		'Minefield',
		'MJ12bot',
		'Mojeek',
		'Mojolicious',
		'MolokaiBot',
		'Moreover',
		'msnbot',
		'MTRobot',
		'Musobot',
		'Nameprotect',
		'Navroad',
		'NearSite',
		'Needle',
		'Nessus',
		'Net Vampire',
		'NetAnts',
		'Netcraft',
		'NetLyzer',
		'NetMechanic',
		'NetNewsWire',
		'NetSeer crawler',
		'NetSpider',
		'Nettrack',
		'Netvibes',
		'NetZIP',
		'newsblur',
		'newspaper',
		'NextGenSearchBot',
		'Nibbler',
		'NICErsPRO',
		'Niki-Bot',
		'Nikto',
		'NimbleCrawler',
		'Nimbostratus',
		'NING',
		'Ninja',
		'Nmap',
		'node-fetch',
		'Not',
		'NPbot',
		'Nuclei',
		'Nutch',
		'Nuzzel',
		'oBot',
		'Octopus',
		'okhttp',
		'omgili',
		'OnalyticaBot',
		'OnCrawl',
		'Openfind',
		'OpenLinkProfiler',
		'OpenVAS',
		'OrangeBot',
		'OrangeSpider',
		'OutclicksBot',
		'OutfoxBot',
		'Page Analyzer',
		'page scorer',
		'PageAnalyzer',
		'PageGrabber',
		'PageScorer',
		'Pandalytics',
		'Panscient',
		'Papa Foto',
		'PaperLiBot',
		'Pavuk',
		'pcBrowser',
		'PeoplePal',
		'PetalBot',
		'petalsearch',
		'Picscout',
		'Picsearch',
		'PictureFinder',
		'Piepmatz',
		'Pimonster',
		'Pingdom',
		'Pinterest',
		'Pixray',
		'PleaseCrawl',
		'plumanalytics',
		'PocketParser',
		'Pockey',
		'PrintfulBot',
		'Probethenet',
		'profound',
		'ProPowerBot',
		'protopage',
		'ProWebWalker',
		'Proximic',
		'Psbot',
		'PulseCrawler',
		'Pump',
		'PxBroker',
		'PyCurl',
		'QueryN Metasearch',
		'QuerySeekerSpider',
		'Quick-Crawler',
		'Qwantify',
		'RankActive',
		'RankFlex',
		'RankingBot',
		'RankurBot',
		'RealDownload',
		'Reaper',
		'RebelMouse',
		'Recorder',
		'RedesScrapy',
		'Reeder',
		'ReGet',
		'RepoMonkey',
		'Ripper',
		'ripz',
		'RocketCrawler',
		'Rogerbot',
		'SalesIntelligent',
		'SBIder',
		'scan.lol',
		'ScanAlert',
		'Scanbot',
		'ScooperBot',
		'ScoutJet',
		'Scrapy',
		'Screaming',
		'ScreenerBot',
		'ScrepyBot',
		'Searchestate',
		'SearchmetricsBot',
		'Seekport',
		'Selfoss',
		'Semanticbot' ,
		'SemanticJuice',
		'SemanticScholarBot',
		'semantic-visions.com',
		'Semrush',
		'SentiBot',
		'SeobilityBot',
		'SEOkicks',
		'SEOkicks-Robot',
		'SEOlyticsCrawler',
		'Seomoz',
		'SEOprofiler',
		'seoscanners',
		'SeoSiteCheckup',
		'SEOstats',
		'SerendeputyBot',
		'serpstatbot',
		'sexsearcher',
		'Shodan',
		'ShowyouBot',
		'Siphon',
		'SISTRIX',
		'Sitebeam',
		'SiteCheck',
		'SiteExplorer',
		'Siteimprove',
		'SiteLockSpider',
		'siteripz',
		'SiteSnagger',
		'SiteSucker',
		'Sitevigil',
		'Sleuth',
		'SlySearch',
		'SmartDownload',
		'SMTBot',
		'SMXCrawler',
		'Snake',
		'Snapbot',
		'Snoopy',
		'SocialRankIOBot',
		'Sociscraper',
		'Sogou web spider',
		'sogouspider',
		'Sosospider',
		'Sottopop',
		'SpaceBison',
		'Spammen',
		'SpankBot',
		'Spanner',
		'Spbot',
		'SpiderLing',
		'Spinn3r',
		'SputnikBot',
		'spyfu',
		'Sqlmap',
		'Sqlworm',
		'Sqworm',
		'Steeler',
		'StormCrawler',
		'Stripper',
		'Sucker',
		'Sucuri',
		'SuperBot',
		'superfeedr',
		'Surfbot',
		'SurveyBot',
		'Suzuran',
		'Swiftbot',
		'sysscan',
		'Szukacz',
		'T0PHackTeam',
		'T8Abot',
		'tAkeOut',
		'Teleport',
		'Telesoft',
		'Telesphoreo',
		'TencentTraveler',
		'The Intraformant',
		'The Knowledge AI',
		'TheNomad',
		'Thumbor',
		'TightTwatBot',
		'Titan',
		'Toata',
		'Toweyabot',
		'Traackr.com',
		'Tracemyfile',
		'trendiction',
		'TrendsmapResolver',
		'True_Robot',
		'TTD-Content',
		'Turingos',
		'Turnitin',
		'Tweetedtimes',
		'TweetmemeBot',
		'TwengaBot',
		'Twice',
		'Twingly',
		'Twitterbot',
		'TwitterFeed',
		'Typhoeus',
		'ubermetrics',
		'UnisterBot',
		'UnwindFetchor',
		'updown_tester',
		'Upflow',
		'urlresolver',
		'Vacuum',
		'Vagabondo',
		'VB Project',
		'V-BOT',
		'VCI',
		'VegeBot',
		'VelenPublicWebCrawler',
		'VeriCiteCrawler',
		'VidibleScraper',
		'Virusdie',
		'VoidEYE',
		'Voil',
		'Voltron',
		'Wallpapers',
		'WASALive-Bot',
		'WBSearchBot',
		'Web Auto',
		'Web Collage',
		'Web Enhancer',
		'Web Fetch',
		'Web Fuck',
		'Web Pix',
		'Web Sauger',
		'Web Sucker',
		'WebAuto',
		'WebBandit',
		'WebCollage',
		'WebCopier',
		'WEBDAV',
		'WebEnhancer',
		'WebFetch',
		'WebFuck',
		'webgains-bot',
		'WebGo IS',
		'WebImageCollector',
		'WebLeacher',
		'webmeup-crawler',
		'WebPix',
		'webpros.com',
		'webprosbot',
		'WebReaper',
		'WebSauger',
		'Webshag',
		'Website Quester',
		'WebsiteExtractor',
		'WebsiteQuester',
		'Webster',
		'WebStripper',
		'WebSucker',
		'WebWhacker',
		'WebZIP',
		'WeSEE',
		'Whack',
		'Whacker',
		'Whatweb',
		'Who.is Bot',
		'WinHTTrack',
		'WiseGuys Robot',
		'WISENutbot',
		'Wonderbot',
		'Woobot',
		'woriobot',
		'Wotbox',
		'wp_is_mobile',
		'Wprecon',
		'WPScan',
		'WWW-Mechanize',
		'WWWOFFLE',
		'Xaldon WebSpider',
		'Xenu',
		'XoviBot',
		'xpymep1.exe',
		'Yahoo',
		'YandexBot',
		'YisouSpider',
		'YoudaoBot',
		'Zade',
		'Zauba',
		'Zermelo',
		'Zeus',
		'Zgrab',
		'Zitebot',
		'ZmEu',
		'Zombiebot',
		'ZoomBot',
		'ZoominfoBot',
		'ZumBot',
		'ZyBorg'
	);

	/**
	 * Get Bot Name by User Agent
	 * @param str $userAgent User Agent
	 * @return string|NULL
	 */
	static public function getName($userAgent)
	{
		foreach(self::$_aBots as $botName)
		{
			if (stripos($userAgent, $botName) !== FALSE)
			{
				return $botName;
			}
		}
		return NULL;
	}
}